version: 2.1

common_parameters: &common_parameters
  os:
    type: enum
    enum: [ alpine, debian, linux, macos, "win/default" ]

## ORBS ##

orbs:
  win: circleci/windows@4.1.1

## EXECUTORS ##

executors:
  alpine:
    resource_class: medium
    docker:
      - image: docker.io/library/alpine:3.16

  debian:
    resource_class: medium
    docker:
      - image: docker.io/library/debian:11

  linux:
    resource_class: medium
    machine:
      image: ubuntu-2004:202101-01

  macos:
    resource_class: medium
    macos:
      xcode: 13.4.1

## COMMANDS ##

commands:
  prepare:
    parameters:
      <<: *common_parameters
    steps:
      # NOTE: minimal effort to allow moving most conditionals out of ci config
      - when:
          condition:
            equal: [ alpine, << parameters.os >> ]
          steps:
            - run: apk add -U make

      - when:
          condition:
            equal: [ debian, << parameters.os >> ]
          steps:
            - run: apt-get update -y && apt-get install -y make

      - when:
          condition:
            equal: [ linux, << parameters.os >> ]
          steps:
            - run: sudo apt-get update -y && sudo apt-get install -y make

      - when:
          condition:
            not:
              equal: [ "win/default", << parameters.os >> ]
          steps:
            - run: make install-deps EXECUTOR=<< parameters.os >>

      - when:
          condition:
            equal: [ "win/default", << parameters.os >> ]
          steps:
            - run: choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=User"'
            - run: choco install ninja

  build:
    parameters:
      <<: *common_parameters
    steps:
      - when:
          condition:
            not:
              equal: [ "win/default", << parameters.os >> ]
          steps:
            - run:
                # NOTE: the circle ci container executor reports the memory/cpu stats
                # of the host machine (https://ideas.circleci.com/ideas/CCI-I-578),
                # `nproc` will return 36 on docker/medium resource_class,
                # ninja parallelizes accordingly, which leads to overloading
                # and circleci eventually terminating the builds:
                #
                # ninja: job failed: /usr/bin/c++ [...]
                # c++: fatal error: Killed signal terminated program cc1plus
                # compilation terminated
                #
                # force overwrite job count here:
                command: make lief JOBS=3

      - when:
          condition:
            equal: [ "win/default", << parameters.os >> ]
          steps:
            - run:
               command: refreshenv & cd vendor\lief & python ./setup.py --ninja build_ext -b ..\..\dist\lief
               shell: cmd.exe

      - persist_to_workspace:
          root: .
          paths:
            - dist/lief

  test:
    steps:
      - attach_workspace:
          at: .

      - run: make check

## JOBS ##

jobs:
  build:
    parameters:
      <<: *common_parameters
    executor: { name: << parameters.os >> }
    steps:
      - checkout
      - prepare:
          os: << parameters.os >>
      - build:
          os: << parameters.os >>
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: postject-api.h
      - store_artifacts:
          path: postject.py
  
  test:
    parameters:
      <<: *common_parameters
    executor: { name: << parameters.os >> }
    steps:
      - checkout
      - prepare:
          os: << parameters.os >>
      - test

## WORKFLOWS ##

build_matrix: &build_matrix
  matrix:
    parameters:
      os: [ alpine, debian, linux, macos, "win/default" ]

test_matrix: &test_matrix
  matrix:
    parameters:
      os: [ alpine, debian, linux, macos ]

workflows:
  postject:
    jobs:
      - build:
          <<: *build_matrix
      - test:
          <<: *test_matrix
          requires: [ build-<<matrix.os>> ]

